In [28]:
import pandas as pd 
import numpy as np
accel_scaling = 100
accel_data = pd.read_csv("0-steady-state_accel.csv")*(9.80665)
variance_ax = accel_data["ax"].var()
variance_ay = accel_data["ay"].var()
variance_az = accel_data["az"].var()
var_accel_array=np.array([variance_ax,variance_ay,variance_az])
scaled_accel_array= var_accel_array*accel_scaling
print(scaled_accel_array)

[0.01017598 0.00434706 0.00143793]


In [27]:
f_scaling = 250
wrench_data = pd.read_csv("0-steady-state_wrench.csv")
variance_fx = wrench_data["fx"].var()
variance_fy = wrench_data["fy"].var()
variance_fz = wrench_data["fz"].var()
var_force_array=np.array([variance_fx,variance_fy,variance_fz])
scaled_force_array= var_force_array*f_scaling
print(scaled_force_array)

[0.30894993 0.11104961 1.40843833]


In [3]:
t_scaling = 5000
variance_tx = wrench_data["tx"].var()
variance_ty = wrench_data["ty"].var()
variance_tz = wrench_data["tz"].var()
var_t_array=np.array([variance_tx,variance_ty,variance_tz])
scaled_t_array= var_t_array*t_scaling
print(scaled_t_array)

[0.00676394 0.01746809 0.00033167]
